### ISSUE TITLE
R5.0 informal testing fixes

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/openmct-mcws#11]
- [x] realtime data
- [x] import/export
- [x] channel tables / channel tables sets should NOT be ordered by timestamp
- [x] clean config.js
- [x] not found object notifications (fixed by #25 )
- [x] deep copy of options causing infinite loop (fixed by #14 )
- [x] channel alarms always aliased (fixed by #25 )
- [x] clean up contributing.md
- [x] data product view
- [x] maxresults not working (mcws sending 5.0B1)
- [x] historical session filter
- [x] packet view
