### ISSUE TITLE
Refactor historical session selector

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/openmct-mcws#29]
The historical session selector currently has view components and table instances open behind the scenes. Refactor to use these components when needed.
```[tasklist]
### Tasks
- [ ] better time conductor snap to session selection (including multiple selection)
- [ ] (request) hyperlinks support
- [ ] (request) generic fields / other time fields
```

**Comment by mudinthewater** [comment]
Is this also a good time to request a couple of improvements! 
1. Can we hyperlinks support? I'd like to put links in the 'description' field that the users can click on to both select the single session and go to the SCET range of said session. 
2. Can we add generic fields? I'd also like to add text start/end times (in SCET/SCLK/Whatever) in my sessions returns, but the columns appear to be hard coded.
